#Auto generated by Edalize
TARGET        = tb_wop_vertical_packing_engine
TOPLEVEL      = tb_wop_vertical_packing_engine

VLOG_DEFINES  = 
VLOG_INCLUDES = -i /home/pxr/workspace/hpu_fpga/hw/module/top_common/rtl/inc -i /home/pxr/workspace/hpu_fpga/hw/module/number_theoretic_transform/module/ntt_core_common/rtl/inc -i /home/pxr/workspace/hpu_fpga/hw/module/pep_mono_mult_acc/module/pep_mmacc_splitc/module/pep_mmacc_splitc_sxt/rtl/inc -i /home/pxr/workspace/hpu_fpga/hw/common_lib/mod_arithmetic/module/mod_reduct/module/mod_reduct_barrett/rtl/coverage -i /home/pxr/workspace/hpu_fpga/hw/module/number_theoretic_transform/module/ntt_core_gf64/module/ntt_core_gf64_network/rtl/inc
GEN_PARAMS    = 

XELAB_OPTIONS =	-debug typical
XSIM_OPTIONS  = -sv_seed 65474897379328 -ignore_coverage

XSIM_WAVE_TCL = /home/pxr/workspace/hpu_fpga/hw/module/pe_pbs/simu/tb_wop_vertical_packing_engine/xsim/tb_wop_vertical_packing_engine/dump_wave.tcl
XSIM_WDB      = /home/pxr/workspace/hpu_fpga/hw/module/pe_pbs/simu/tb_wop_vertical_packing_engine/xsim/tb_wop_vertical_packing_engine/wave.wdb
