#! /usr/bin/bash
# BSD 3-Clause Clear License
# Copyright © 2025 ZAMA. All rights reserved.

cli="$*"

###################################################################################################
# This script deals with the testbench run for WoP-PBS Vertical Packing Engine.
# This testbench has specificities that cannot be handled by run_edalize alone.
# They are handled here.
###################################################################################################

# aliases are not expanded when the shell is not interactive.
# Redefine here for more clarity
run_edalize=${PROJECT_DIR}/hw/scripts/edalize/run_edalize.py

module="tb_wop_vertical_packing_engine"

###################################################################################################
# usage
###################################################################################################
function usage () {
echo "Usage : run.sh runs the simulation for $module."
echo "./run.sh [options]"
echo "Options are:"
echo "-h                       : print this help."
echo "-g                       : GLWE_K (default 1)"
echo "-W                       : MOD_Q_W: modulo width (default 32)"
echo "-q                       : MOD_Q: modulo (default 2**32)"
echo "-B                       : MAX_BIT_WIDTH: Maximum bit width (default 20)"
echo "-N                       : N_LVL1: LWE dimension level 1 (default 1024)"
echo "-L                       : ELL_LVL1: GGSW decomposition level (default 3)"
echo "-i                       : Regfile number of registers (default 64)"
echo "-j                       : Regfile number of coefficients (default 32)"
echo "-k                       : Regfile number of sequences (default 4)"
echo "-- <run_edalize options> : run_edalize options."

}

###################################################################################################
# input arguments
###################################################################################################

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

run_edalize_args=""
GEN_STIMULI=1
GLWE_K=1  # K parameter for TLWE
MAX_BIT_WIDTH=20
MOD_Q_W=32
MOD_Q=$((2**32))
N_LVL1=1024
ELL_LVL1=3
REGF_NB_REG=64
REGF_COEF_NB=32
REGF_NB_SEQ=4

# Initialize your own variables here:
while getopts "hg:W:q:B:N:L:i:j:k:" opt; do
  case "$opt" in
    h)
      usage
      exit 0
      ;;
    g)
      GLWE_K=$OPTARG
      ;;
    W)
      MOD_Q_W=$OPTARG
      ;;
    q)
      MOD_Q=$OPTARG
      ;;
    B)
      MAX_BIT_WIDTH=$OPTARG
      ;;
    N)
      N_LVL1=$OPTARG
      ;;
    L)
      ELL_LVL1=$OPTARG
      ;;
    i)
      REGF_NB_REG=$OPTARG
      ;;
    j)
      REGF_COEF_NB=$OPTARG
      ;;
    k)
      REGF_NB_SEQ=$OPTARG
      ;;
  esac
done

shift $((OPTIND-1))

if [ "${1:-}" = "--" ]; then
  shift
  run_edalize_args="$*"
fi

###################################################################################################
# parameters generation
###################################################################################################

cd "$(dirname "$0")"

# Generate parameter definition file
cat << EOF > gen/param_tfhe_definition_pkg.sv
// Auto-generated parameter definition file for Vertical Packing Engine
// Generated by: $0 $cli
// Date: $(date)

package param_tfhe_definition_pkg;
  parameter int GLWE_K = $GLWE_K;
  parameter int MAX_BIT_WIDTH = $MAX_BIT_WIDTH;
  parameter int MOD_Q_W = $MOD_Q_W;
  parameter longint MOD_Q = $MOD_Q;
  parameter int N_LVL1 = $N_LVL1;
  parameter int ELL_LVL1 = $ELL_LVL1;
endpackage
EOF

cat << EOF > gen/regf_common_definition_pkg.sv
// Auto-generated regfile parameter definition file
// Generated by: $0 $cli
// Date: $(date)

package regf_common_definition_pkg;
  parameter int REGF_NB_REG = $REGF_NB_REG;
  parameter int REGF_COEF_NB = $REGF_COEF_NB;
  parameter int REGF_NB_SEQ = $REGF_NB_SEQ;
  
  // Additional parameters for regfile addressing
  localparam int REGF_ADDR_W = \$clog2(REGF_NB_REG);
  localparam int REGF_RD_REQ_W = REGF_ADDR_W + 16;
  localparam int REGF_WR_REQ_W = REGF_ADDR_W + 16;
endpackage
EOF

echo "Generated parameter files with:"
echo "  GLWE_K = $GLWE_K"
echo "  MAX_BIT_WIDTH = $MAX_BIT_WIDTH"
echo "  MOD_Q_W = $MOD_Q_W"
echo "  N_LVL1 = $N_LVL1"
echo "  ELL_LVL1 = $ELL_LVL1"

###################################################################################################
# run edalize
###################################################################################################

# Set PROJECT_DIR if not set
if [ -z "${PROJECT_DIR}" ]; then
    export PROJECT_DIR="$(cd ../../../.. && pwd)"
fi

# Set default simulation tool if not set
if [ -z "${PROJECT_SIMU_TOOL}" ]; then
    export PROJECT_SIMU_TOOL="xsim"
fi

echo "Running: $run_edalize -m $module -t $PROJECT_SIMU_TOOL -d $(pwd) $run_edalize_args"

# Execute with output filtering to reduce noise
echo "=== Starting build process (filtering repetitive warnings) ==="
$run_edalize -m $module -t $PROJECT_SIMU_TOOL -d $(pwd) $run_edalize_args 2>&1 | \
grep -v "WARNING> Same file given several times" | \
grep -v "INFO: " | \
grep -v "instead of:" | \
grep -v "use:" | \
tee /tmp/build_output.log | \
grep -E "(ERROR|CRITICAL|FATAL|SUCCESS|PASS|FAIL|Done|failed|error|Test|Compiling|Building|Elaborating|Starting|Finished)" -i

# Capture exit code
exit_code=${PIPESTATUS[0]}

# Show build summary
echo ""
echo "=== Build Summary ==="
if [ $exit_code -eq 0 ]; then
    echo "✅ Build completed successfully"
else
    echo "❌ Build failed with exit code: $exit_code"
    echo "Last few lines of output:"
    tail -10 /tmp/build_output.log | grep -v "WARNING> Same file given several times"
fi

exit $exit_code